server:
  port: 8070

spring:
  application:
    name: eureka-server #指定服务名称
eureka:
  instance:
    #hostname: localhost #指定主机地址
    prefer-ip-address: true #默认使用本地ip 也可以显示的配置使用上面的hostname指定ip
  client:
    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: false #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      defaultZone: http://localhost:8070/eureka/
  server:
    enable-self-preservation: false #关闭保护模式