server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: false
      gateway:
        routes:
          id: method_route
          uri: http://www.baidu.com
          predicates:
          - Method=GET

#客户端注册到 eureka服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
