server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
       - id: test-gateway
         uri: https://cloud.spring.io/spring-cloud-gateway/reference/html
         predicates:
          - Path=/test/** #跳不过去
      discovery:
        locator:
          enabled: false #开启从注册中心动态创建路由的功能 true-开启 false-关闭
          lower-case-service-id: false #使用小写服务名，默认是大写

#客户端注册到 eureka服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
