server:
  #端口
  port: 8091

spring:
  #应用
  application:
    name: auth-web

  #数据库
  datasource:
    url: jdbc:mysql://123.56.252.124:3306/o2o?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #这里注意一下 数据库的账户密码要配置在hikari这里不然的话不能连接成功数据库
      username: root
      password: 123456root
      #自动提交
      auto-commit: true
      #等待连接池分配连接的最大时长(毫秒),超过这个时长还没可用的连接则发生SQLException,默认:30秒
      connection-timeout: 30000
      #最小连接数
      minimum-idle: 5
      #最大连接数
      maximum-pool-size: 20
      #连接超时的最大时长(毫秒),超时则被释放(retired),默认:10分钟
      idle-timeout: 600000
      #连接池名字
      pool-name: DataSourceHikariCP
      #连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      max-lifetime: 28740000
      connection-test-query: select 1

  #jpa配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true


#服务注册
dubbo:
  #服务名称
  application:
    name: auth-web-provider
  #注册中心地址
  registry:
    address: zookeeper://123.56.252.124:2181
  #服务端口
  protocol:
    port: 6666
    id: auth-web-provider
  provider:
    timeout: 6000
