server:
  port: 8061
  servlet:
    context-path: /order
spring:
  application:
    name: order-web

#客户端注册到 eureka服务中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
    register-with-eureka: true
    fetch-registry: true

feign:
  hystrix:
    enabled: true
