server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      gateway:
        routes:
          id: order-web
          uri: http://www.baidu.com
          predicates:
          - Method=GET

#客户端注册到 eureka服务中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
